export const SET_PENDING = 'SET_PENDING'
export const DELETE_PENDING = 'DELETE_PENDING'

export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_USER_HIGHFIVES_COUNT = 'SET_USER_HIGHFIVES_COUNT'
export const SET_CHAT_USER = 'SET_CHAT_USER'

export const SET_NEAREST_USERS = 'SET_NEAREST_USERS'

export const SET_MY_HIGHFIVES = 'SET_MY_HIGHFIVES'
export const SET_ALL_HIGHFIVES = 'SET_ALL_HIGHFIVES'
